In [1]:
import pandas as pd
import numpy as np
import warnings
import os

cwd = os.getcwd()
missing_routing = os.path.join(cwd, "client_data", "Routing - Factory.xlsx")

warnings.filterwarnings("ignore")

In [2]:
df_missing_routing=pd.read_excel(missing_routing,sheet_name='II. FGs_missing_routing.',skiprows=2)

df_missing_routing=df_missing_routing[['Factory', 'Item Code', 'Crew\nTotal ', 'Run Rate (Primary UOM)\nFG', 'Power Usage\nFG']].rename(columns={
    'Crew\nTotal ': 'Crew Total',
    'Run Rate (Primary UOM)\nFG': 'Run Rate (Primary UOM FG)',
    'Power Usage\nFG': 'Power Usage FG'
})

df_missing_routing=df_missing_routing.rename(columns={
    'Factory':'Unit'})

conditions = [
    df_missing_routing['Unit'].isin(['NF1', 'NF2']),
    df_missing_routing['Unit'] == 'GFM',
    df_missing_routing['Unit'] == 'KPF'
]
choices = ['NFC', 'GFC', 'KFC']
df_missing_routing['FACTCode'] = np.select(conditions, choices, default=None)

df_missing_routing

,Unit,Item Code,Crew Total,Run Rate (Primary UOM FG),Power Usage FG,FACTCode
0,NF2,4001972056,26,70.0,9.00,NFC
1,GFM,4001971946,36,240.0,9.00,GFC
2,GFM,4001971947,36,240.0,9.00,GFC
3,GFM,4001971948,28,125.0,9.00,GFC
4,NF2,4001380891,34,134.0,16.00,NFC
...,...,...,...,...,...,...
201,GFM,4001111270,34,134.0,16.00,GFC
202,NF1,4001972168,34,134.0,16.00,NFC
203,NF1,4001972128,35,240.0,63.52,NFC
204,NF1,4001972129,35,240.0,63.52,NFC
205,NF1,4001972159,34,134.0,16.00,NFC

In [3]:
df_missing_routing.to_excel('Missing_routing.xlsx',index=False)